# AWS Secret Manager
# non-prod/demo/production-service/secrets
#Key/Vale -> app/<?> 
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
# Any Name Give Secret Name
    name: production-service
    creationPolicy: Owner
  data:
# Add Key Name Here
  - secretKey: app 
    remoteRef:
      key: non-prod/demo/production-service/secrets
#Add Same key Name Here
      property: app
